### PR TITLE
Built signup and sign in functionalities

### PR DESCRIPTION
**Pull request by aimanbasri**
Built the sign up functionality using Django's built-in UserCreationForm, with an unstyled template and routed the the appropriate URLs.

URLs:

http://127.0.0.1:8000/signup/
http://127.0.0.1:8000/login/

### CODE REVIEW

**Review by ShafiqAiman — CHANGES_REQUESTED** [review]
Can you please tell us briefly about these codes? And is there anything that we need to install? I tried to run the Django server and I got errors.

**Comment by aimanbasri** [comment]
> Can you please tell us briefly about these codes? And is there anything that we need to install? I tried to run the Django server and I got errors.

If you're free now/anytime, let's have a call and see how these codes run on others' PC.

**Comment by ShafiqAiman** [comment]
I am free now anyway if you want to give me a call. @aimanbasri

**Review by ShafiqAiman — COMMENTED** [review]
Okay lah everything is good "for now"

**Review by ShafiqAiman — COMMENTED** [review]
@aimanbasri Based on the discussion that we had just now, do you agree if we close this pull request first since there will be changes to these files once you start implementing Vue.js?

**Comment by aimanbasri** [comment]
> @aimanbasri Based on the discussion that we had just now, do you agree if we close this pull request first since there will be changes to these files once you start implementing Vue.js?

Yeah I'll just put this pull request as a draft one.

**Pull request closed without merging**
